# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NBAStatsPlus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NBAStatsPlus
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'

  target 'NBAStatsPlusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NBAStatsPlusUITests' do
    # Pods for testing
  end

end
